services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mlops-frontend
    restart: on-failure
    env_file:
      - .env
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
        loki-retries: 5
        loki-batch-size: 50
        labels: "service,container_name"
    ports:
      - 7860:7860
    networks:
      - aivn-network

networks:
  aivn-network:
    external: true
