services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mlops-backend
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/v1/health"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 15s
    volumes:
      - ./DATA:/DATA
    env_file:
      - .env
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
        loki-retries: 5
        loki-batch-size: 50
        labels: "service,container_name"
    ports:
      - 8000:8000
    networks:
      - aivn-network

networks:
  aivn-network:
    external: true
